{% set version = "0.11.0" %}
{% set sha256 = "6fc874a37582c35964c672424e65c940579b5e0fbd74bdb41015a21833643eb7" %}
package:
  name: pycalphad
  version: {{ version }}

source:
  fn: pycalphad-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pycalphad/pycalphad-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [py2k]
  skip: true  # [py<39]
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - cython >=0.24
    - numpy >=2.0                            # [python_impl != "pypy"]
    - scipy
    - pip
    - python
    - scipy
    - setuptools
    - setuptools_scm >=6.0
  run:
    - cython >=0.24
    - matplotlib-base >=3.3
    - pint
    - pyparsing >=2.4
    - pytest
    - pytest-cov
    - python
    - python-symengine >=0.9.2
    - runtype
    - scipy
    - setuptools-scm >=6.0
    - symengine >=0.9
    - tinydb >=3.8
    - typing-extensions # drop when pycalphad drops support for Python<3.13
    - xarray >=0.11.2

test:
  imports:
    - pycalphad
    - pycalphad.core
    - pycalphad.io
    - pycalphad.plot
  commands:
    - pip check
    - pypy -c "import os, sysconfig as sc; os.unlink(os.path.join(sc.get_paths()['platstdlib'], '__init__.py'))" || true # workaround for conda-forge/pycalphad-feedstock#55
    - pytest --pyargs pycalphad
  requires:
    - pip

about:
  home: https://pycalphad.org/
  license: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: CALPHAD tools for designing thermodynamic models, calculating phase diagrams and investigating phase equilibria.
  doc_url: https://docs.pycalphad.org/
  dev_url: https://github.com/pycalphad/pycalphad

extra:
  recipe-maintainers:
    - richardotis
    - bocklund
