{% set version = "0.10.4.post1" %}
{% set sha256 = "ee9282e949e4b10b81eec8230f3b69bb74839c45561eb6c4708d49b47937553a" %}
package:
  name: pycalphad
  version: {{ version }}

source:
  fn: pycalphad-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pycalphad/pycalphad-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [py2k]
  skip: true  # [py<38]
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython >=0.24
    - numpy
    - scipy
    - pip
    - python
    - scipy
    - setuptools
    - setuptools_scm >=6.0
  run:
    - cython >=0.24
    - importlib_resources  # drop when pycalphad drops support for Python<3.9
    - matplotlib-base >=3.3
    - {{ pin_compatible('numpy') }}
    - pyparsing >=2.4
    - pytest
    - pytest-cov
    - python
    - python-symengine >=0.9.2
    - scipy
    - setuptools_scm >=6.0
    - symengine >=0.9
    - tinydb >=3.8
    - xarray >=0.11.2

test:
  imports:
    - pycalphad
    - pycalphad.core
    - pycalphad.io
    - pycalphad.plot
  commands:
    - pip check
    - pytest --pyargs pycalphad
  requires:
    - pip

about:
  home: https://pycalphad.org/
  license: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: CALPHAD tools for designing thermodynamic models, calculating phase diagrams and investigating phase equilibria.
  doc_url: https://docs.pycalphad.org/
  dev_url: https://github.com/pycalphad/pycalphad

extra:
  recipe-maintainers:
    - richardotis
    - bocklund
