{% set version = "0.8.5" %}
{% set sha256 = "5d7d55e7f68947df387e4f76edad82391a17fb3e97d70cbf72ae5306dcd135ab" %}
package:
  name: pycalphad
  version: {{ version }}

source:
  fn: pycalphad-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pycalphad/pycalphad-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - sympy.patch  # this patch can be removed with the next release

build:
  skip: true  # [py2k]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cyipopt >=0.3
    - cython >=0.24
    - matplotlib-base
    - numpy >=1.13
    - pyparsing
    - python
    - python-symengine ==0.6.1
    - scipy
    - setuptools
    - symengine ==0.6.0
    - sympy ==1.7
    - tinydb >=3.8
    - xarray >=0.11.2

  run:
    - cyipopt >=0.3
    - cython >=0.24
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - pyparsing
    - python
    - python-symengine ==0.6.1
    - scipy
    - symengine ==0.6.0
    - sympy ==1.7
    - tinydb >=3.8
    - xarray >=0.11.2

test:
  imports:
    - pycalphad
    - pycalphad.core
    - pycalphad.io
    - pycalphad.plot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pycalphad.org/
  license: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: CALPHAD tools for designing thermodynamic models, calculating phase diagrams and investigating phase equilibria.
  doc_url: https://docs.pycalphad.org/
  dev_url: https://github.com/pycalphad/pycalphad

extra:
  recipe-maintainers:
    - richardotis
    - bocklund
