{% set version = "0.10.5" %}
{% set sha256 = "cf0605407b49bf5e50a25ab935be485e59685c5a1ffc5ea7d1dca945a14a8be7" %}
package:
  name: pycalphad
  version: {{ version }}

source:
  fn: pycalphad-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pycalphad/pycalphad-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [py2k]
  skip: true  # [py<38]
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - cython >=0.24
    - numpy
    - scipy
    - pip
    - python
    - scipy
    - setuptools
    - setuptools_scm >=6.0
  run:
    - cython >=0.24
    - importlib_resources  # drop when pycalphad drops support for Python<3.9
    - matplotlib-base >=3.3
    - {{ pin_compatible('numpy') }}
    - pyparsing >=2.4
    - pytest
    - pytest-cov
    - python
    - python-symengine >=0.9.2
    - scipy
    - setuptools_scm >=6.0
    - symengine >=0.9
    - tinydb >=3.8
    - xarray >=0.11.2

test:
  imports:
    - pycalphad
    - pycalphad.core
    - pycalphad.io
    - pycalphad.plot
  commands:
    - pip check
    - pypy -c "import os, sysconfig as sc; os.unlink(os.path.join(sc.get_paths()['platstdlib'], '__init__.py'))" || true # workaround for conda-forge/pycalphad-feedstock#55
    - pytest --pyargs pycalphad
  requires:
    - pip

about:
  home: https://pycalphad.org/
  license: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: CALPHAD tools for designing thermodynamic models, calculating phase diagrams and investigating phase equilibria.
  doc_url: https://docs.pycalphad.org/
  dev_url: https://github.com/pycalphad/pycalphad

extra:
  recipe-maintainers:
    - richardotis
    - bocklund
