{% set version = "0.7.1.post2" %}
{% set sha256 = "b2efef313e5c8b3ac2b6eb8f30c041d1e05c99ae425b50be020a7c93d426fcc2" %}
package:
  name: pycalphad
  version: {{ version }}

source:
  fn: pycalphad-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pycalphad/pycalphad-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 1000
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - setuptools
    - matplotlib
    - pandas
    - nose
    - mock
    - xarray !=0.8
    - sympy >=1.2
    - pyparsing
    - tinydb
    - scipy
    - dask >=0.18
    - distributed
    - numpy >=1.13
    - dill
    - cyipopt
  run:
    - python
    - cython
    - matplotlib
    - pandas
    - xarray !=0.8
    - sympy >=1.2
    - pyparsing
    - tinydb
    - scipy
    - dask >=0.18
    - distributed
    - {{ pin_compatible('numpy') }}
    - dill
    - cyipopt

test:
  imports:
    - pycalphad
    - pycalphad.core
    - pycalphad.io
    - pycalphad.plot

about:
  home: https://pycalphad.org/
  license: MIT
  summary: 'CALPHAD tools for designing thermodynamic models, calculating phase diagrams and investigating phase equilibria.'
  doc_url: https://docs.pycalphad.org/
  dev_url: https://github.com/pycalphad/pycalphad

extra:
  recipe-maintainers:
    - richardotis
    - bocklund
