{% set version = "0.7" %}
{% set sha256 = "b11862cbd547a206991153f6057f089238d27798e0ce197568fc9aa4a79ecc2d" %}
package:
  name: pycalphad
  version: {{ version }}

source:
  fn: pycalphad-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pycalphad/pycalphad-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - cython
    - setuptools
    - matplotlib
    - pandas
    - nose
    - mock
    - xarray !=0.8
    - sympy
    - pyparsing
    - tinydb
    - scipy
    - dask >=0.15
    - distributed
    - numpy >=1.9
    - dill
    - cyipopt
  run:
    - python
    - cython
    - matplotlib
    - pandas
    - xarray !=0.8
    - sympy
    - pyparsing
    - tinydb
    - scipy
    - dask >=0.15
    - distributed
    - numpy >=1.9
    - dill
    - cyipopt

test:
  imports:
    - pycalphad
    - pycalphad.core
    - pycalphad.io
    - pycalphad.plot

about:
  home: https://pycalphad.org/
  license: MIT
  summary: 'CALPHAD tools for designing thermodynamic models, calculating phase diagrams and investigating phase equilibria.'
  doc_url: https://docs.pycalphad.org/
  dev_url: https://github.com/pycalphad/pycalphad

extra:
  recipe-maintainers:
    - richardotis
    - bocklund
