{% set version = "0.9.0" %}
{% set sha256 = "340703a84f869c05d3a24d70bcdd731fe3e9b27c90281a72b77d1b4c4f818208" %}
package:
  name: pycalphad
  version: {{ version }}

source:
  fn: pycalphad-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pycalphad/pycalphad-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [py2k]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython >=0.24
    - importlib_metadata  # drop when pycalphad drops support for Python<3.8
    - matplotlib-base >=3.3
    - numpy >=1.13
    - pyparsing >=2.4
    - pytest
    - pytest-cov
    - python >=3.7
    - python-symengine ==0.7.2
    - scipy
    - setuptools
    - setuptools_scm >=6.0
    - symengine ==0.7.2
    - sympy ==1.8
    - tinydb >=3.8
    - xarray >=0.11.2

  run:
    - cython >=0.24
    - importlib_metadata  # drop when pycalphad drops support for Python<3.8
    - matplotlib-base >=3.3
    - {{ pin_compatible('numpy') }}
    - pyparsing >=2.4
    - pytest
    - pytest-cov
    - python >=3.7
    - python-symengine ==0.7.2
    - scipy
    - setuptools_scm >=6.0
    - symengine ==0.7.2
    - sympy ==1.8
    - tinydb >=3.8
    - xarray >=0.11.2

test:
  imports:
    - pycalphad
    - pycalphad.core
    - pycalphad.io
    - pycalphad.plot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pycalphad.org/
  license: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: CALPHAD tools for designing thermodynamic models, calculating phase diagrams and investigating phase equilibria.
  doc_url: https://docs.pycalphad.org/
  dev_url: https://github.com/pycalphad/pycalphad

extra:
  recipe-maintainers:
    - richardotis
    - bocklund
