{% set version = "0.8.1.post1" %}
{% set sha256 = "4c171fe018be4de7a7fc1dfbb5a8f5714a1ac0065f27cd444b83653659e079dd" %}
package:
  name: pycalphad
  version: {{ version }}

source:
  fn: pycalphad-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pycalphad/pycalphad-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - matplotlib
    - pandas
    - nose
    - mock
    - xarray >=0.11.2
    - sympy ==1.4
    - pyparsing
    - tinydb >=3.8
    - scipy
    - dask >=1.2.0
    - distributed
    - numpy >=1.13
    - dill
    - cython >=0.24
    - cyipopt
    - python-symengine ==0.5.1
    - symengine ==0.5.0

  run:
    - python
    - matplotlib
    - pandas
    - xarray >=0.11.2
    - sympy ==1.4
    - pyparsing
    - tinydb >=3.8
    - scipy
    - dask >=1.2.0
    - distributed
    - {{ pin_compatible('numpy') }}
    - cython >=0.24
    - dill
    - cyipopt
    - python-symengine ==0.5.1
    - symengine ==0.5.0

test:
  imports:
    - pycalphad
    - pycalphad.core
    - pycalphad.io
    - pycalphad.plot

about:
  home: https://pycalphad.org/
  license: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'CALPHAD tools for designing thermodynamic models, calculating phase diagrams and investigating phase equilibria.'
  doc_url: https://docs.pycalphad.org/
  dev_url: https://github.com/pycalphad/pycalphad

extra:
  recipe-maintainers:
    - richardotis
    - bocklund
