appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: DFK5RlrtOw/5FZtUHQwKdpT4ILTXd0E71ozTRT1FPyenS05BCHnMmGDYl1iqVtgcwz3tJQIa6TFf+0s/QsoTZAJ7PxlxDSI7wh6Hp57K6Jvzr5TbCn6a+1JSj23ERzWP+hiu1oKtxzix/pxtS6kLq0JsQqI9H3QXgfr90iPzfOT/EgWIzAX6IkRBMRluGqcbVjcp1MZtzrlCYVWPmArNi5JixzsI5igRWf59XD1sLkDS26nozpABftXehnvX12UivK+7ev/l7iQV7yyyeQjSjFhFvzm+4OdM2/ooHwMGxqeqLK+vRSMTXarQSpyeVn99FAf0gWJBHyaR0UL6ix/D+gr7NA8ETm+iMnku9v28ZAvyicSUeu8IHFpUBW0cJRn7rx7yIRA6ACr27CJeiK0kB5TfpWdbBxjtlBBmdZbcA8wctwt9lElK/ZmxKg0TvjSdbgzDXn3J6fpY+zFCo6lh8jtpQvGTJ9IfAcrGHAxc7cvNRxcY8v3YB7r6v1BpnoCOtGySYVaQ0nO/w8luyOmUtsUOTtuWLCEV18MM7Jd4qmtoP5LsvU6up4hlRdWgiTUf754X5y8z2TDAJ7GWTY/IxWQ1HiAFlybMjq4JMojkXmirvYYcwxXVZwcQGO059dmD19Uw73b24Fhr1Re4g2kUcNkguzYilFon0xSBxmogH5Y=}
