travis:
  secure:
    BINSTAR_TOKEN: PoOZMmhG3W90GEUlJ0c/3gXdmHlJICOSq0LxS0i8ERsd1Iz176Ja6w6Q1OP9rr/GStZ6Xd0EuysmcLbJ4bHZHAAqk/9TTaz3hq1Jl+yio3j5g903zmxYxaD1CGI7C8A0Z+Rp6bBMdtFa5RIVPN56NcgIia61slyHk9+fTCIpVrVWMtJp6Ypn0H9Ds4rcYeCsOd7wbOGWgqeB9K+qw0Oud3gsBa9GVNExHvCeGKI7xBxfltr957jTMikX4cxU5uTw3EPYNC2f69Gk+FHIDZwG4S/vn1XkXvcy5UxMS9uNAx6k04EVpvTjiMPDJdKbX9lNiZF3ZLHcLy2ZPc9cwzJRWzU+ZCu0F0qok3NUUTTFT0aY8b1VR4baLoAq6RUUE04sXRD4UfLjbAIaMzJLlRoVBLsJ33Co6yjw9cJ2XVhLdhPod0WmjJRrE3i2Q424TCfrmWpmnFPUlKZmZ9Go7OUNU1juHlx+VAmd7nduBUHi1I4Culsq7Zr2cH7PSECkVceSuOMoaWXf+hivUZtl+GiHUGVLqkPobY2XtNLM0gc7YQXo/evocBisZmtApwRcQtkI5Heosx+ZrQktwi5gbA9Z5loiIBEcWgIBkRm3PG3ch2tmaQMpgu9cCcwfECTr0qyoPAocxyv5ULgge17pxIJNaV+/1pR3tcVVYmwWIoAmaTY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
